language: python
sudo: false
python:
  - "2.7"
  - "3.3"
before_install:
  # Install the coverage utility and coveralls reporting utility
  - pip install coverage
  - pip install coveralls
  # FIXME (18-Apr-2016) cnx-easybake requires an unreleased package, cssselect2
  - pip install git+https://github.com/Connexions/cssselect2.git#egg=cssselect2
  # Install cnx-easybake
  - pip install git+https://github.com/Connexions/cnx-easybake.git#egg=cnx-easybake
install:
  - python setup.py install
before_script:
  - pip install pep8
  - pep8 --exclude=tests *.py cnxepub/
  - pep8 --max-line-length=1000 cnxepub/tests
script:
  - coverage run --source=cnxepub -m unittest discover
after_success:
  # Report test coverage to coveralls.io
  - coveralls
notifications:
  email: false
