language: python
sudo: false
python:
  - "2.7"
  - "3.3"
before_install:
  # Install the coverage utility and coveralls reporting utility
  - pip install coverage
  - pip install coveralls
install:
  - python setup.py install
before_script:
  - pip install pep8
  - pep8 --exclude=tests *.py cnxepub/
script:
  - coverage run --source=cnxepub -m unittest discover
after_success:
  # Report test coverage to coveralls.io
  - coveralls
notifications:
  email: false
